name: AlisQI assignment

services:
  appserver:
    type: php:8.2
    composer_version: 2-latest
    via: cli
    build:
      - composer install

tooling:
  calculate:
    service: appserver
    description: Run calculations
    cmd: php calculator.php
